let knowledge=[];
let selectedCategory="All";
let selectedGuideId="";
const CATEGORY_RULES={Deposit:["deposit","top up","topup","put money","add money","fund account","money in","bank in","cannot deposit","can't deposit","deposit error","deposit failed"],Withdrawal:["withdraw","withdrawal","cash out","cashout","money out","take money out","cannot withdraw","can't withdraw","withdraw pending","withdrawal pending","payout"],"Special Bonus":["bonus","special bonus","promo","promotion","reward","risk bonus","grace period","claim bonus","bonus claim","eligible bonus","reload bonus"],"APP / Technical":["app","iphone","ios","android","download app","install app","app cannot install","login app","technical","application"]};
const CATEGORY_WORDS={Deposit:["deposit","top up","put money","add money","deposit error"],Withdrawal:["withdraw","cash out","pending","paylock"],"Special Bonus":["bonus","promotion","claim bonus","risk bonus","grace period"],"APP / Technical":["app","iPhone","iOS","Android","install"]};
const ICONS={All:"◇",Deposit:"↗",Withdrawal:"↓","Special Bonus":"★","APP / Technical":"⌁"};
const STEP_TITLES=["Confirm the issue","Check the backend","Take the required action","Verify the result","Guide the member","Complete the process"];
const $=id=>document.getElementById(id);
const norm=value=>String(value||"").toLowerCase().replace(/\s+/g," ").trim();
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const terms=value=>norm(value).split(/[^a-z0-9]+/).filter(word=>word.length>2);

function syncTheme(){try{document.documentElement.dataset.theme=parent.documentElement.dataset.theme||"dark"}catch(_){document.documentElement.dataset.theme="dark"}}
syncTheme();
try{new MutationObserver(syncTheme).observe(parent.documentElement,{attributes:true,attributeFilter:["data-theme"]})}catch(_){}

function categoryScore(category,query){const text=norm(query);let score=0;const hits=[];for(const keyword of CATEGORY_RULES[category]||[]){if(text.includes(keyword)){score+=keyword.includes(" ")?8:4;hits.push(keyword)}}if(category==="Special Bonus"&&/(bonus|promo|promotion|reward)/.test(text))score+=6;if(category==="Deposit"&&/(deposit|top up|topup|put money|add money)/.test(text))score+=3;return{category,score,hits:[...new Set(hits)]}}
function detectCategory(query){return Object.keys(CATEGORY_RULES).map(category=>categoryScore(category,query)).filter(result=>result.score>0).sort((a,b)=>b.score-a.score)[0]||null}
function guideScore(item,query){const text=norm(query);if(!text)return 1;const words=terms(query);let score=0;const title=norm(item.title),category=norm(item.category),summary=norm(item.summary);if(title.includes(text))score+=12;if(category.includes(text))score+=10;if(norm(item.brand).includes(text))score+=5;for(const keyword of item.keywords||[]){const key=norm(keyword);if(text===key)score+=9;else if(text.includes(key)||key.includes(text))score+=6;for(const word of words)if(key.includes(word))score+=2}for(const word of words){if(title.includes(word))score+=3;if(category.includes(word))score+=2;if(summary.includes(word))score+=1}return score}
function bestGuide(query,category){return knowledge.filter(item=>item.category===category).map(item=>({item,score:guideScore(item,query)})).sort((a,b)=>b.score-a.score)[0]||null}

function renderCategories(){const categories=["All",...Object.keys(CATEGORY_RULES)];$("categories").innerHTML=categories.map(category=>{const count=category==="All"?knowledge.length:knowledge.filter(item=>item.category===category).length;return`<button type="button" class="category-btn ${selectedCategory===category?"active":""}" data-category="${esc(category)}"><span>${ICONS[category]}</span>${esc(category)} <em>${count}</em></button>`}).join("")}
function currentResults(){const query=$("search").value;return knowledge.filter(item=>selectedCategory==="All"||item.category===selectedCategory).map(item=>({item,score:guideScore(item,query)})).filter(row=>!norm(query)||row.score>0).sort((a,b)=>b.score-a.score)}
function renderResults(){const rows=currentResults();$("resultsTitle").textContent=selectedCategory==="All"?"All knowledge":selectedCategory;$("resultCount").textContent=`${rows.length} guide${rows.length===1?"":"s"}`;$("results").innerHTML=rows.length?rows.map(({item})=>`<button type="button" class="result-card ${selectedGuideId===item.id?"active":""}" data-guide="${esc(item.id)}"><strong>${esc(item.title)}</strong><span class="result-meta"><span>${esc(item.category)}</span><span>${esc(item.brand)}</span></span></button>`).join(""):`<div class="empty-results">No matching guide. Try a broader keyword or another category.</div>`}

function renderDetection(query){const detected=detectCategory(query),box=$("detection");box.hidden=false;if(!detected){box.innerHTML=`<div class="detection-main"><div class="detection-icon">?</div><div class="detection-copy"><small>NO TOPIC DETECTED</small><strong>Try adding more details</strong><div class="chip-row"><span class="chip">deposit</span><span class="chip">withdrawal</span><span class="chip">bonus</span><span class="chip">app</span></div></div></div>`;return}const words=detected.hits.length?detected.hits:CATEGORY_WORDS[detected.category],best=bestGuide(query,detected.category);box.innerHTML=`<div class="detection-main"><div class="detection-icon">${ICONS[detected.category]}</div><div class="detection-copy"><small>CATEGORY DETECTED</small><strong>${esc(detected.category)}</strong><div class="chip-row">${words.slice(0,6).map(word=>`<span class="chip">${esc(word)}</span>`).join("")}</div>${best?`<div class="recommendation"><div><span>RECOMMENDED SOP</span><b>${esc(best.item.title)}</b></div><button type="button" class="secondary-btn" data-open-guide="${esc(best.item.id)}">Open guide</button></div>`:""}</div><span class="match-score">${Math.min(98,70+detected.score*2)}% MATCH</span></div>`}

function renderGuide(item){if(!item)return;selectedGuideId=item.id;renderResults();$("detail").innerHTML=`<div class="guide-content"><div class="guide-top"><div><span class="eyebrow">${esc(item.category)}</span><h2>${esc(item.title)}</h2><div class="guide-meta">${esc(item.brand)}</div></div><div class="guide-actions"><button type="button" class="primary-btn" data-copy>Copy reply</button><button type="button" class="secondary-btn" data-picture>Picture guide</button></div></div><div class="guide-summary">${esc(item.summary)}</div><div class="guide-section-title">STEP-BY-STEP GUIDE</div><ol class="steps">${item.steps.map((step,index)=>`<li><span class="step-num">${index+1}</span><div class="step-copy"><b>${STEP_TITLES[index]||"Next step"}</b><span>${esc(step)}</span></div></li>`).join("")}</ol>${item.bonus_amounts?.length?`<div class="guide-section-title">BONUS REFERENCE</div><ul class="bonus-list">${item.bonus_amounts.map(amount=>`<li>${esc(amount)}</li>`).join("")}</ul>`:""}<div class="guide-section-title">IMPORTANT</div><div class="warning"><strong>Check before proceeding</strong>${esc(item.warning)}</div><div class="guide-section-title">REPLY TEMPLATE</div><div class="example">${esc(item.example)}</div><div id="pictureSlot"></div></div>`;$("detail").scrollIntoView({behavior:"smooth",block:"nearest"})}
async function copyReply(item){try{await navigator.clipboard.writeText(item.example)}catch(_){const area=document.createElement("textarea");area.value=item.example;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove()}const toast=$("copyToast");toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1400)}
function togglePicture(item){const slot=$("pictureSlot");if(slot.firstChild){slot.innerHTML="";return}slot.innerHTML=`<img class="guide-image" src="${esc(item.image)}" alt="${esc(item.title)} picture guide" />`}

$("detectBtn").addEventListener("click",()=>renderDetection($("customerMessage").value));
$("customerMessage").addEventListener("input",event=>{if(!norm(event.target.value))$("detection").hidden=true});
$("search").addEventListener("input",renderResults);
document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();$("search").focus()}});
$("categories").addEventListener("click",event=>{const button=event.target.closest("[data-category]");if(!button)return;selectedCategory=button.dataset.category;renderCategories();renderResults()});
$("results").addEventListener("click",event=>{const button=event.target.closest("[data-guide]");if(button)renderGuide(knowledge.find(item=>item.id===button.dataset.guide))});
$("detection").addEventListener("click",event=>{const button=event.target.closest("[data-open-guide]");if(button)renderGuide(knowledge.find(item=>item.id===button.dataset.openGuide))});
$("detail").addEventListener("click",event=>{const item=knowledge.find(entry=>entry.id===selectedGuideId);if(!item)return;if(event.target.closest("[data-copy]"))copyReply(item);if(event.target.closest("[data-picture]"))togglePicture(item)});

async function init(){try{knowledge=await(await fetch("knowledge.json")).json();renderCategories();renderResults();renderDetection($("customerMessage").value)}catch(_){$("results").innerHTML=`<div class="empty-results">Knowledge could not be loaded. Refresh and try again.</div>`}}
init();
