let knowledge=[];
const CATEGORY_RULES={Deposit:["deposit","top up","topup","put money","add money","fund account","money in","bank in","cannot deposit","can't deposit","deposit error","deposit failed"],Withdrawal:["withdraw","withdrawal","cash out","cashout","money out","take money out","cannot withdraw","can't withdraw","withdraw pending","withdrawal pending","payout"],"Special Bonus":["bonus","special bonus","promo","promotion","reward","risk bonus","grace period","claim bonus","bonus claim","eligible bonus","reload bonus"],"APP / Technical":["app","iphone","ios","android","download app","install app","app cannot install","login app","technical","application"]};
const CATEGORY_WORDS={Deposit:["deposit","top up","put money","add money","cannot deposit","deposit error","deposit failed","multiple request"],Withdrawal:["withdraw","withdrawal","cash out","pending","cannot withdraw","paylock","withdraw again"],"Special Bonus":["bonus","promo","promotion","reward","claim bonus","eligible","risk bonus","grace period"],"APP / Technical":["app","iphone","ios","android","download","install","login","technical"]};
const norm=s=>(s||"").toLowerCase().replace(/\s+/g," ").trim();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const terms=q=>norm(q).split(/[^a-z0-9]+/).filter(w=>w.length>2);
function catScore(category,q){let score=0,hits=[];const t=norm(q);for(const kw of CATEGORY_RULES[category]||[]){if(t.includes(kw)){score+=kw.includes(" ")?8:4;hits.push(kw)}}if(category==="Special Bonus"&&/(bonus|promo|promotion|reward)/.test(t))score+=6;if(category==="Deposit"&&/(deposit|top up|topup|put money|add money)/.test(t))score+=3;return {score,hits:[...new Set(hits)]}}
function detectCategory(q){return Object.keys(CATEGORY_RULES).map(category=>({category,...catScore(category,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)[0]||null}
function score(item,q){const t=norm(q);if(!t)return 0;const words=terms(q);let s=0;const title=norm(item.title),cat=norm(item.category),summary=norm(item.summary);if(title.includes(t))s+=12;if(cat.includes(t))s+=10;if(norm(item.brand).includes(t))s+=5;for(const kw of item.keywords){const k=norm(kw);if(t===k)s+=9;else if(t.includes(k)||k.includes(t))s+=6;for(const w of words)if(k.includes(w))s+=2}for(const w of words){if(title.includes(w))s+=3;if(cat.includes(w))s+=2;if(summary.includes(w))s+=1}return s}
function specificMatch(q,category){return knowledge.filter(k=>k.category===category).map(k=>({k,s:score(k,q)})).sort((a,b)=>b.s-a.s)[0]||null}
function highlight(text,words){let out=esc(text);for(const w of words.filter(x=>x.length>2).sort((a,b)=>b.length-a.length)){const re=new RegExp(`(${w.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")})`,"gi");out=out.replace(re,"<mark>$1</mark>")}return out}
function icon(cat){return cat==="Deposit"?"↗":cat==="Withdrawal"?"↓":cat==="Special Bonus"?"★":"⌁"}
function detectMessage(q){const box=document.getElementById("detection"),cat=detectCategory(q);if(!cat){box.classList.add("hidden");return}box.classList.remove("hidden");const words=cat.hits.length?cat.hits:CATEGORY_WORDS[cat.category].slice(0,4);const exact=specificMatch(q,cat.category);const has=exact&&exact.s>8;box.innerHTML=`<div class="detect-main"><div class="detect-top"><div class="detect-icon">${icon(cat.category)}</div><div><small>CATEGORY DETECTED</small><b>${esc(cat.category)}</b></div><span class="match">${Math.min(98,70+cat.score*2)}% MATCH</span></div><div class="detect-label">RECOMMENDED WORDS</div><div class="chips">${words.slice(0,7).map(w=>`<mark>${esc(w)}</mark>`).join("")}</div>${has?`<div class="specific"><span class="bolt">⚡</span><div><small>RECOMMENDED SOP</small><b>${esc(exact.k.title)}</b></div><button id="openSop">OPEN GUIDE</button></div>`:""}</div>${!has?`<div class="soft">Category detected. Browse the related knowledge below or search a more specific issue.</div>`:""}`;if(has)box.querySelector("#openSop").onclick=()=>show(exact.k,words)}
function render(q=""){
  const old=document.getElementById("searchResults");
  if(old) old.remove();
  q=norm(q);
  if(!q) return;
  const rows=knowledge.map(k=>({k,s:score(k,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,5);
  const section=document.createElement("section");
  section.id="searchResults";
  section.className="search-results";
  section.innerHTML=`<div class="sectionline"><span>SEARCH RESULTS</span><small>${rows.length} guide${rows.length===1?"":"s"}</small></div>` +
    (rows.length ? `<div class="results-list">${rows.map(({k})=>`<div class="result-card" data-id="${k.id}"><div><b>${highlight(k.title,terms(q))}</b><small>${esc(k.category)} · ${esc(k.brand)}</small></div><span>›</span></div>`).join("")}</div>` : `<div class="empty search-empty">No guide found. Try a category or keyword.</div>`);
  const anchor=document.getElementById("settings");
  anchor.parentNode.insertBefore(section,anchor);
  section.querySelectorAll(".result-card").forEach(x=>x.onclick=()=>show(knowledge.find(k=>k.id===x.dataset.id),terms(q)));
}

function stepTitle(step,i){const titles=["Confirm the issue","Check the backend","Take the required action","Verify the result","Guide the member","Complete the process"];return titles[i]||"Next step"}
async function copyExample(item,btn){try{await navigator.clipboard.writeText(item.example);btn.textContent="✓ Copied Example";setTimeout(()=>btn.textContent="COPY MESSAGE",1400)}catch(e){const ta=document.createElement("textarea");ta.value=item.example;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();btn.textContent="✓ Copied Example";setTimeout(()=>btn.textContent="COPY MESSAGE",1400)}}
function show(item,words=[]){const d=document.getElementById("detail");const sr=document.getElementById("searchResults");if(sr)sr.classList.add("hidden");d.classList.remove("hidden");d.innerHTML=`<div class="detail-top"><div class="back" id="back">← Back to knowledge</div><div class="detail-head"><div><h2>${esc(item.title)}</h2><div class="detail-summary">${highlight(item.summary,words)}</div></div><div class="badge">${esc(item.category)}</div></div><div class="why"><div class="why-title">WHY THIS GUIDE WAS RECOMMENDED</div><div class="why-chips">${(words.length?words:["Recommended"]).slice(0,7).map(w=>`<mark>✓ ${esc(w)}</mark>`).join("")}</div></div></div><div class="guide"><div class="guide-title"><i>✓</i> STEP-BY-STEP GUIDE</div><ol class="steps">${item.steps.map((s,i)=>`<li><span class="num">${i+1}</span><div class="steptext"><b>${stepTitle(s,i)}</b>${highlight(s,words)}</div></li>`).join("")}</ol></div><div class="warn"><b>⚠ Important point</b>${highlight(item.warning,words)}</div><div class="examplebox"><div class="example-label">EXAMPLE</div><div class="example">${esc(item.example)}</div></div><div class="actions"><button class="btn copy" id="copy">COPY MESSAGE</button><button class="btn pic" id="pic">🖼 PICTURE GUIDE</button></div>`;d.querySelector("#back").onclick=()=>{d.classList.add("hidden");const sr=document.getElementById("searchResults");if(sr)sr.classList.remove("hidden");};d.querySelector("#copy").onclick=()=>copyExample(item,d.querySelector("#copy"));d.querySelector("#pic").onclick=()=>{const old=d.querySelector("img");if(old){old.remove();return}const img=document.createElement("img");img.src=item.image;img.alt=item.title+" picture guide";d.appendChild(img)}}
document.getElementById("search").addEventListener("input",e=>{render(e.target.value);detectMessage(e.target.value)});document.getElementById("detectBtn").onclick=()=>detectMessage(document.getElementById("customerMessage").value);document.getElementById("customerMessage").addEventListener("input",e=>detectMessage(e.target.value));document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>{document.getElementById("search").value="";const sr=document.getElementById("searchResults");if(sr)sr.remove();document.getElementById("detail").classList.add("hidden");detectMessage(b.dataset.q)});
async function init(){knowledge=await (await fetch("knowledge.json")).json();detectMessage(document.getElementById("customerMessage").value)}init();
